apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc
  custom.css: ""
  custom.js: ""
  background: "https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80"
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Social:
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com/
              description: The front page of the internet
        - Wykop:
            - href: https://wykop.pl/
              description: Glupie Obrazki

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    - Services:
        - PiHole:
            icon: pi-hole.png
            href: "https://pihole.lokaal.tuntelder.com/admin"
            description: DNS Ad Blocker
        - Grafana:
            icon: grafana.png
            href: "https://grafana.lokaal.tuntelder.com"
            description: Metrics
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: "https://jellyfin.lokaal.tuntelder.com"
            description: Media platform
        - Jellyseerr:
            icon: jellyseerr.png
            href: "https://jellyseerr.lokaal.tuntelder.com"
            description: Media Request Platform
        - Sonarr: 
            icon: sonarr.png
            href: "https://sonarr.lokaal.tuntelder.com"
            description: TV Show Search
        - Prowlarr:
            icon: prowlarr.png
            href: "https://prowlarr.lokaal.tuntelder.com"
            description: TV Show Search
        - Radarr:
            icon: radarr.png
            href: "https://radarr.lokaal.tuntelder.com/"
            description: Movies Search
        - QBitTorrent:
            icon: qbittorrent.png
            href: "https://qbittorrent.lokaal.tuntelder.com/"
            description: Torrent Downloads
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false

    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank

    - openmeteo:
        label: Current
        latitude: 50.088079
        longitude: 19.930431
        cache: 5
        units: metric

    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
  docker.yaml: ""
