apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant
  namespace: homeassistant
subsets:
  - addresses:
      - ip: 10.0.100.11
    ports:
      - port: 8123
