---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.ingress.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-service
          kind: TraefikService
          namespace: edge
  tls:
    certResolver: letsencrypt
