apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  ports:
    - port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant
  namespace: homeassistant
subsets:
  - addresses:
      - ip: 10.0.100.11
    ports:
      - port: 8123
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.tuntelder.com`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123
  tls:
    certResolver: letsencrypt
