apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: homeassistant-tcp
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`home.ingress.tuntelder.com`)
      services:
        - name: homeassistant-tcp
          port: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-tcp
  namespace: homeassistant
spec:
  ports:
    - port: 8123
      protocol: TCP
  externalIPs:
    - 10.0.100.11
