apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-assistant-forward
  namespace: homeassistant
spec:
  forward:
    address: http://10.0.100.11:8123
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: home-assistant-service
  namespace: homeassistant
spec:
  weighted:
    services:
      - name: home-assistant-forward
        weight: 1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.ingress.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-service
          kind: TraefikService
          namespace: homeassistant
  tls:
    certResolver: letsencrypt
