lapi:
  enabled: false
  service:
    type: ClusterIP
    port: 8080

  # Inject env from your ExternalSecret-managed Secret
  extraEnvFrom:
    - secretRef:
        name: crowdsec-api-token
        key: ENROLL_KEY
  bouncers:
    traefik:
      keyFromSecret:
        name: crowdsec-api-token
        key: TRAEFIK_BOUNCER_KEY

console:
  enabled: true
  service:
    type: ClusterIP
    port: 8081

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik