---
container_runtime: containerd

lapi:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
  externalSecret:
    name: crowdsec-api-token
    csLapiSecretKey: csLapiSecret
    registrationTokenKey: registrationToken
  env: 
    - name: ENROLL_INSTANCE_NAME
      value: "my-k8s-cluster"
    - name: ENROLL_TAGS
      value: "k8s linux test"
    - name: CS_LAPI_SECRET
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: csLapiSecret
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: registrationToken
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: ENROLL_KEY
    - name: TRAEFIK_BOUNCER_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: TRAEFIK_BOUNCER_KEY

  bouncers:
    traefik:
      keyFromSecret:
        name: crowdsec-api-token
        key: TRAEFIK_BOUNCER_KEY

console:
  enabled: true
  service:
    type: ClusterIP
    port: 8081

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik


