lapi:
  enabled: true
  service:
    type: ClusterIP
    port: 8080


  bouncers:
    traefik:
      key: "temp-super-secret-static-key-@9fj20F92_2djdksl2" # for testing only

agent:
  # we are not setting up traefik but the acquisition section is required.
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik