---
lapi:
  enabled: true
  service:
    type: ClusterIP
    port: 8080

  extraEnvFrom:
    - secretRef:
        name: crowdsec-api-token

  bouncers:
    traefik:
      keyFromSecret:
        name: crowdsec-api-token
        key: TRAEFIK_BOUNCER_KEY

console:
  enabled: true
  service:
    type: ClusterIP
    port: 8081

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
