---
lapi:
  enabled: true
  service:
    type: ClusterIP
    port: 8080

  extraEnv:
    - name: ENROLL_INSTANCE_NAME
      value: "my-k8s-cluster"
    - name: ENROLL_TAGS
      value: "k8s linux test"

  extraEnvFrom:
    - secretRef:
        name: crowdsec-api-token

  bouncers:
    traefik:
      keyFromSecret:
        name: crowdsec-api-token
        key: TRAEFIK_BOUNCER_KEY
        
console:
  enabled: true
  service:
    type: ClusterIP
    port: 8081

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
