---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-access-logs
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: traefik-access-logs  
  storageClassName: longhorn