image:
  repository: "linuxserver/jellyfin"
  tag: "10.10.7"

ports:
  - name: main
    containerPort: 8096

ingress:
  host: jellyfin.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: local-only
      namespace: edge

envs:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: JELLYFIN_PublishedServerUrl
    value: "jellyfin.tuntelder.com"

health:
  enabled: true
  startupProbeSeconds: 220

pvcs:
  - name: jellyfin-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/config/jellyfin
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /config
  - name: jellyfin-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: false     # allow root start
  runAsUser: 0            # start as root
  fsGroup: 1000           # ensure mounted volumes writable
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
