---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    releaseName: authentik
    namespace: authentik
    version: 2.2.1
    includeCRDs: true
    valuesFile: ./values.yaml

