apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: edge
data:
  encom-tower.yaml: |
    entries:
      # Authentik Application
      - model: authentik_core.application
        attrs:
          name: encom
          slug: encom
          policy_engine_mode: any
        state: present

      # OAuth2 Provider
      - model: authentik_providers_oauth2.oauth2provider
        attrs:
          name: encom
          client_type: confidential
          include_claims_in_id_token: true
          sub_mode: hashed_user_id
          issuer_mode: per_provider
          access_code_validity: minutes=1
          access_token_validity: hours=24
          refresh_token_validity: days=30
          redirect_uris:
            - matching_mode: strict
              url: https://auth.ingress.tuntelder.com/outpost.goauthentik.io/callback?X-authentik-auth-callback=true
            - matching_mode: strict
              url: https://auth.ingress.tuntelder.com?X-authentik-auth-callback=true
        state: present

      # Proxy Provider
      - model: authentik_providers_proxy.proxyprovider
        attrs:
          name: encom
          mode: forward_domain
          external_host: https://auth.ingress.tuntelder.com
          cookie_domain: .ingress.tuntelder.com
          intercept_header_auth: true
          internal_host_ssl_validation: true
          access_token_validity: hours=24
          refresh_token_validity: days=30
        state: present
