---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-cluster-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: authentik_postgres-password
        property: password
    - secretKey: secret-key
      remoteRef:
        key: authentik_secret-key
        property: password
