---
global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: authentik-secret
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-secret
    - name: AUTHENTIK_BOOTSTRAP_USERNAME
      valueFrom:
        secretKeyRef:
          key: bootstrap_username
          name: authentik-secret
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: bootstrap_password
          name: authentik-secret
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - auth.kube.tuntelder.com
    tls:
      - hosts:
          - auth.kube.tuntelder.com
        secretName: tls-kube-tuntelder-com

  readinessProbe:
    httpGet:
      path: /-/health/ready/
      port: http
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

  livenessProbe:
    httpGet:
      path: /-/health/live/
      port: http
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    existingSecret: authentik-secret
    secretKeys:
      password: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
