---
global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: authentik-secret
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-secret

server:
  extraEnvFrom:
    - secretRef:
        name: authentik-secret
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    hosts:
      - auth.traefik.tuntelder.com
    tls:
      - hosts:
          - auth.traefik.tuntelder.com
  volumes:
    - name: custom-css
      configMap:
          name: authentik-custom-css
  volumeMounts:
    - name: custom-css
      mountPath: /web/dist/custom.css
      subPath: custom.css
      
  readinessProbe:
    httpGet:
      path: /-/health/ready/
      port: http
      scheme: HTTP
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: /-/health/live/
      port: http
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    existingSecret: authentik-secret
    secretKeys:
      password: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
