---
global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: authentik-secret
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-secret
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - auth.kube.tuntelder.com
    tls:
      - hosts:
          - auth.kube.tuntelder.com
        secretName: tls-kube.tuntelder.com
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi

worker:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi

postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    existingSecret: authentik-secret
    secretKeys:
      password: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
