authentik:
  secret_key: "replace-with-secure-random-hex" # generate: openssl rand -hex 32
  error_reporting:
    enabled: true
  postgresql:
    password: "bkLAFJX6oU"

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.kube.tuntelder.com


postgresql:
  enabled: true
  auth:
    password: "bkLAFJX6oU"

redis:
  enabled: true
