authentik:
    secret_key: "NqTZvFj3Lrrkm2uCJrulSCxCUB4FZLj0dOyXKIK6qBSZIuMwHh"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "bQ7+ArmOit0ATqUAh/o1fQATmN6MNcisgt4+ir41q8VZVP03KUWxNoZt7M+PoNGG6sKr3S2MO/BrCKUl"

server:
    ingress:
    ingressClassName: nginx
    enabled: true
    hosts: 
        - authentik.kube.tuntelder.com
    tls:
        enabled: true
        secretName: tls-kube.tuntelder.com
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 10000m
postgresql:
    enabled: true
    auth:
        password: "bQ7+ArmOit0ATqUAh/o1fQATmN6MNcisgt4+ir41q8VZVP03KUWxNoZt7M+PoNGG6sKr3S2MO/BrCKUl"
redis:
    enabled: true