---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    helm.sh/resource-policy: keep
  behavior: merge
