---
{{- range .Values.pvcs }}
{{- if eq .type "nfs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.name}}-pv
spec:
  capacity:
    storage: {{ .size | default "1000Gi" }}
  accessModes:
    - {{ .accessMode | default "ReadWriteMany" }}
  nfs:
    server: {{ .server }}
    path: {{ .path }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}
{{- end }}
