---
{{- if .Values.pvcs }}
{{- range .Values.pvcs }}
{{- if eq .type "longhorn" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessMode }}
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .size | default "1000Gi" }}
  volumeName: {{ .name }}-pv
  storageClassName: ""
{{- end }}
{{- end }}
{{- end }}
