---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-preupgrade
  namespace: longhorn-system
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["settings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["longhorn.io"]
    resources: ["engineimages"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-preupgrade-binding
  namespace: longhorn-system
subjects:
  - kind: ServiceAccount
    name: longhorn-service-account
    namespace: longhorn-system
roleRef:
  kind: Role
  name: longhorn-preupgrade
  apiGroup: rbac.authorization.k8s.io
