---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: edge
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.69.201
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443
    - name: admin
      port: 8080
      targetPort: 8080
  selector:
    app: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  namespace: edge
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: traefik.traefik.tuntelder.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  name: admin
  tls:
    - hosts:
        - "traefik.traefik.tuntelder.com"
