#ENC[AES256_GCM,data:woTvHPmdXh4PAFUfW1Yn8NZWVAUAx+kATRlFhu5TgEmJOID/uMYm,iv:AxgtP26nQ0/4zuAAlP0fKtq5iPbL7sDwhJDTMXkXrmI=,tag:j2Cfnxbmim04gfc2AlxKkg==,type:comment]
apiVersion: ENC[AES256_GCM,data://4=,iv:QZCdgovTi5x3QVhq1+5m9gBRNii86Xs+iJjlYeEbvj0=,tag:dpg6CcvxuFx+lpQGR+Q23g==,type:str]
kind: ENC[AES256_GCM,data:ny6SY0as,iv:sO9EPGg51RsSkkuz887xC/0R+z75cATgvS7efdMnx+U=,tag:R8ChcOn7nztaQxpGMueRdg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bKRcVdT6olkFMz1VN2i2GguOfYnlHZLPSRRZ,iv:Mx8gckNdWDgUNGF+vR2jk2+CfLpECX8wuLj/6Eq+tRo=,tag:InBj6nD4dkVE0F/VsqPQ3g==,type:str]
    namespace: ENC[AES256_GCM,data:DoWmTNlI3g==,iv:JLXz1pYWBhM75oDiY+9xOf/F2LLuO268EZdpMJdOIFU=,tag:OG2MIgQJWOet8EXSNnyJLw==,type:str]
type: ENC[AES256_GCM,data:0BCKSbbl,iv:cTvsKmc/yYo3i25JZ9tFffvSFmMNjcu0AsQyKqKD2Gk=,tag:gf3mGOUPJdKaH9t5Cw/4Mg==,type:str]
stringData:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:9wW19omBkoYkhRKDD8W/2RtmelB/EQ0MBiRi2CTqgZS2IbYpDsMVTQ==,iv:LzCp/9TUnotZwVUYKewPyMB69zLLY1VwnkBzIRj9UbI=,tag:gut8I+maFWZAgitBdrmTQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9y7pmg6tpdhkjtm70mxtu688n28m6qc40ld670708dn8fru8qls0znr8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QTdQc0lWTERDbnk5b3ZO
            d0NsQkJTQkxnV0J3UDBwbkMrZm9UL1MwWkg4ClQ5dzdmWmdhMUdFTkpLakp0Ukht
            a2tETHhhcjU5Z2oyOXFKVDRlRjNlUjgKLS0tIDBVWUlYS05uUnBZMWcxcGora1Ex
            Rk5yT2hyYXp3Q0VmK2tzdzM2UmRjZHMK/X66rN0aBoQCb04RZwdSMDp2eoMS3x+A
            s2FF+CbwRuWPopJ4+mbu3spPitxVpxBA9Uwr8G44phwXCjPon29Dug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T10:18:22Z"
    mac: ENC[AES256_GCM,data:2FglVQ3nRZ594oGl5CHBdoluWr2zsGQlVQiMWcG6uaRlMRgpVtSm3d6Dyav3EiCSxc4xBqPu9F1Uu0eYLj/OVoCikUoIFDCQcqUXxXlC/8cVToMk6F7Z/9mHs3B2iNEZRBhQ2DPHtU33xj1vwnxmULZxwWCX6jvFvHeS5TyhqGw=,iv:O8qfY0Uf5OXOp38hR8IFm6OCuPQA+EKSZ55db0izgq0=,tag:BIOsJDNHWhBNfTP6Qez/rw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
