apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - roles.yaml
  - volumes.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: base-domain-config
    literals:
      - BASE_DOMAIN={{ .Values.baseDomain }}