apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - roles.yaml
  - volumes.yaml
  - deployment.yaml
  - service.yaml

vars:
  - name: DOMAIN
    objref:
      kind: ConfigMap
      name: app-config
      apiVersion: v1
    fieldref:
      fieldpath: data.domain