apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
