name: Enforce single commit PR

on:
  pull_request:
    branches: [ main ]

jobs:
  single-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check number of commits
        run: |
          COMMITS=$(gh pr view ${{ github.event.pull_request.number }} --json commits -q ".commits")
          if [ "$COMMITS" -gt 1 ]; then
            echo "PR has more than one commit. Please squash into a single commit."
            exit 1
          fi
