name: Rewrite Default Commit Messages
on:
  push:
    branches:
      - main

jobs:
  randomize-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo apt-get update && sudo apt-get install -y git-filter-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Rewrite commits with the default message
          git filter-repo --message-callback '
import random, string
if message.decode() == "Default Commit Message\n":
    message = "".join(random.choices(string.ascii_letters + string.digits, k=8)).encode()
message
'

      - run: git push origin main --force
