---
name: Validate Terraform
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "**"

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [./infrastructure/helios, ./infrastructure/atlas]
    steps:
      - uses: actions/checkout@v5

      - name: Terraform validate
        uses: dflook/terraform-validate@v2
        with:
          path: ${{ matrix.dir }}
