name: Validate Terraform
on:
  push:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find Terraform root directories
        id: find_dirs
        run: |
          dirs=$(find . -type f -name "*.tf" \
                | grep -v "/modules/" \
                | xargs -n1 dirname \
                | sort -u \
                | tr '\n' ' ')
          echo "dirs=$dirs" >> $GITHUB_OUTPUT

      - name: Validate Terraform configurations
        run: |
          for dir in ${{ steps.find_dirs.outputs.dirs }}; do
            echo "Validating $dir"
            cd $dir
            terraform init -backend=false
            terraform validate
            cd - > /dev/null
          done
