---
name: Validate Manifest References
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check manifest references
        run: |
          python3 .github/scripts/validate_manifests.py
