---
name: Validate Terraform
on:  # yamllint disable-line rule:truthy
  push:
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Validate Terraform configuration (encom-tower)
        uses: devops-infra/action-terraform-validate@v0.3.1
        with:
          working-directory: infrastructure/terraform/encom-tower
      - name: Validate Terraform configuration (identity-disc)
        uses: devops-infra/action-terraform-validate@v0.3.1
        with:
          working-directory: infrastructure/terraform/identity-disc
